-- MySQL Script generated by MySQL Workbench
-- Wed Dec 16 16:03:29 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema sgusers
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sgusers
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sgusers` DEFAULT CHARACTER SET utf8 ;
USE `sgusers` ;

-- -----------------------------------------------------
-- Table `sgusers`.`Player`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgusers`.`Player` (
  `tempNickName` VARCHAR(30) NOT NULL,
  `mainNickName` VARCHAR(30) NOT NULL,
  `family` VARCHAR(30) NULL,
  `profileLink` VARCHAR(75) NOT NULL,
  `sgid` VARCHAR(17) NOT NULL,
  `bmid` VARCHAR(10) NOT NULL DEFAULT 0,
  `isAdmin` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`sgid`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
